### PR TITLE
composer: bump to PHPUnit 4.5

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
There should be a redirect then.

**Comment by logical-and** [comment]
This library seems like abandoned. I cannot make it, unfortunately.

**Comment by TomasVotruba** [comment]
Oh, I see. And the library you linked is it's successor maintained by you? If so, I might help there then.

**Comment by logical-and** [comment]
Self-nominated successor. :) I just fix many issues and refactored a lot to bring back library to life.
If you want to help with maintaining - you are welcome.

**Comment by logical-and** [comment]
I just added you as collaborator

**Comment by TomasVotruba** [comment]
Thanks. I do exactly the same for [ApiGen project](https://github.com/apigen/), so I know what you mean :)

Will check later, thanks for your trust.

**Comment by logical-and** [comment]
I saw you your project ApiGen, and I think you not just a passer-by. :) Nice generators, btw.

**Pull request closed without merging**
