### PR TITLE
Extract oauth1 response parsing

### PR DESCRIPTION
**Pull request by hanneskaeufler**
- Removes a ton of duplication in the OAuth 1 token response parsing
- Move default parsing behaviour into OAuth1\Services\AbstractService instead of repeating it in every single Subclass
- remove oauth 1 service tests which now just duplicate the parser tests

### CODE REVIEW

**Comment by elliotchance** [comment]
@hanneskaeufler please resolve merge conflicts.

**Comment by hanneskaeufler** [comment]
I'll have a look at it in a few days. Being a year old I'm little scared if this is not a ton of work. Fingers crossed.

**Comment by hanneskaeufler** [comment]
Whoah, that was easy, lucky me :sunglasses:

**Comment by elliotchance** [comment]
@Lusitanian I will leave this one up to you :smile:

**Pull request closed without merging**
