### PR TITLE
Added doctrine cache support as storage

### PR DESCRIPTION
**Pull request by cmodijk**
Like the tile it ads support to use the doctrine cache to store the tokens.

### CODE REVIEW

**Comment by logical-and** [comment]
Hey. :)
Can you please open pull request at [updated library](https://github.com/logical-and/php-oauth), so I will be able to merge your changes.

**Comment by cmodijk** [comment]
I'm not using this library any more and don't have a lot of time.

**Comment by logical-and** [comment]
Ok, but which one library you use?

**Comment by cmodijk** [comment]
I'm using my own fork of this library but never used the doctrine cache implementation. I created this pull request because i noticed there where a lot of implementations using different storages backends and i think we should let the backends be handled by a separate library like the `doctrine/cache` library.

**Comment by logical-and** [comment]
@cmodijk `doctrine/cache` is an good idea. Maybe, the next step of this idea - is create common classes-builders, what implements different doctrine cache providers (redis, file, memory, memcache, etc) and one generic class, which allow to use custom doctrine cache provider (like you do)?

**Comment by cmodijk** [comment]
I think the basic idea is create an interface and create separate library's with implementations of this. One implementation is `doctrine/cache` one other is `SymfonySession` like in this library.

**Comment by logical-and** [comment]
@cmodijk Well, I guess `OAuth\Common\Storage\TokenStorageInterface` is the interface you talking about. I will separate custom storage providers soon.

**Comment by cmodijk** [comment]
Yes that's what i mean! I forgot al about that interface.

**Comment by logical-and** [comment]
Ok, thank you for ideas. I create issue in bug tracker. If you will have a time available, I will add you as collaborator.

**Comment by cmodijk** [comment]
@logical-and For me to be a collaborator i need the response object and de PSR-7 integration because we use Yammer see #144 and #335 for the details without the request giving back a response object i can't integrate it in any project of ours. Let me know what you think on my last comment at #335.

**Comment by cmodijk** [comment]
I'm closing this because we don't use it and nobody is using it.

**Pull request closed without merging**
