### PR TITLE
travis: PHP 7.0 nightly added

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
7.0 will be out in few months. I think it's user-friendly to make sure package will work on this version.

**Comment by logical-and** [comment]
The command "pyrus install pear/PHP_CodeSniffer" failed and exited with 134 during .
https://travis-ci.org/Lusitanian/PHPoAuthLib/jobs/57294297

**Comment by TomasVotruba** [comment]
I'd recommend using code sniffer installed by composer, since PEAR is really deprecated tool.

**Comment by logical-and** [comment]
Can you please open pull request at [updated library](https://github.com/logical-and/php-oauth), so I will be able to merge your changes.

**Pull request closed without merging**
