### PR TITLE
Add ability to refresh Yahoo token

### PR DESCRIPTION
**Pull request by dooplenty**

### CODE REVIEW

**Comment by logical-and** [comment]
I will add this one in updated library. Thank you.

**Comment by Lusitanian** [comment]
Thanks :D Sorry for delay, going to try to start maintaining a bit better.

**Comment by PedroAmorim** [comment]
Hi! 
This merge change name in composer.json in commit b9d5e2e , fail merge?

**Comment by Lusitanian** [comment]
@PedroAmorim ope...yeah, fixed

**Pull request merged**
