### PR TITLE
Stripe OAuth connection - Basic

### PR DESCRIPTION
**Pull request by lussn**
I implemented a basic Stripe connection and I want to share it with you.
Tschüsie

### CODE REVIEW

**Comment by golevel** [comment]
What's the status on this?

**Comment by DavidSporer** [comment]
Hey guys, could this please be merged? Would really help me :-)

**Comment by lussn** [comment]
@Lusitanian here you have the tests. I totally forgot about this. It could be useful if you merge it. Thanks

**Comment by elliotchance** [comment]
@lussn it cannot be merged until the build is green :smile:

**Comment by lussn** [comment]
@elliotchance I think build is not working. This library is not updated anymore. :(

**Comment by lussn** [comment]
I'll take a look

**Comment by elliotchance** [comment]
@lussn the build is actually failing because of some style issues with code that isn't yours. If you pull in the latest changes from master they should go away.

**Comment by lussn** [comment]
thanks @elliotchance ;)

**Comment by commandantp** [comment]
Hi, what's the status on that one? Is it working? :)

**Comment by elliotchance** [comment]
The build is failing. @lussn will need to merge in the latest `master` to get the build working.

**Comment by loweoj** [comment]
@lussn Had a chance to look at this?

**Comment by lussn** [comment]
@Lusitanian Sorry about the delay. I'm ashamed about that. Now I cleaned the watched repos and I can be aware of this kind of things. Here you have the Stripe integration. We're using it in the company, so it works fine. Sorry for the delay again guys. Cheers

**Comment by alexkilty** [comment]
@Lusitanian Will this be merged with `master`?

**Pull request merged**
