### PR TITLE
Intuit QuickBooks

### PR DESCRIPTION
**Pull request by elliotchance**

### CODE REVIEW

**Comment by elliotchance** [comment]
@Lusitanian first green PR in a while...

**Comment by elliotchance** [comment]
Actually there is a defect. I am not storing the extra parameters in the token correctly.

**Comment by elliotchance** [comment]
Removed the offending code. Ready for review.

**Comment by cesutherland** [comment]
I've started using this... looks good to me so far!

**Comment by cesutherland** [comment]
For what it's worth, I stumbled a bit setting for testing in their sandbox.  Here's that bit:

```php
    $this->service = $serviceFactory->createService(
      'QuickBooks',
      $this->credentials,
      $this->storage,
      null,
      new Uri('https://sandbox-quickbooks.api.intuit.com/')
    );
```

Also, errors from QBO were a lot more verbose using the curl client:

```php
    use OAuth\Common\Http\Client\CurlClient;
    $serviceFactory->setHttpClient(new CurlClient());
```

**Comment by elliotchance** [comment]
@cesutherland thanks for that. Not sure if it's related but I ran into a QuickBooks known issue where they have said that if your using a sandbox company you must use the production URLs for authentication only because the sandbox auth does not work.

They didn't give an ETA on when this would be fixed so I didn't want to hard code anything hacky like that into the auth process, so I hope they resolve it soon as to not cause more confusion.

**Comment by natsu90** [comment]
Hey guys, I'm getting `HTTP/1.1 401 Unauthorized` error, what did I miss? It thrown at function `requestAccessToken`. I'm using its laravel wrapper, `artdarek/oauth-4-laravel`, and my code is as below,

````
        $token = Input::get('oauth_token');
		$verifier = Input::get( 'oauth_verifier' );
		$companyId = Input::get('realmId');
		$quickbooksService = OAuth::consumer('QuickBooks');

		if( !empty( $token ) && !empty( $verifier ) ) {
          // would throw 401 error
			$access_token = $quickbooksService->requestAccessToken($token, $verifier);

			$result = $quickbooksService->request('/v3/company/'.$companyId.'/account/1');
			print_r(json_decode($result, true));
		} else {

			$request_token = $quickbooksService->requestRequestToken();
			$url = $quickbooksService->getAuthorizationUri(array('oauth_token' => $request_token->getRequestToken()));
			return Redirect::to( (string)$url );
		}
````

**Comment by elliotchance** [comment]
@natsu90 are you trying to connect to a sandbox or production company?

**Comment by natsu90** [comment]
@elliotchance Production company. Or is it because it's on trial subscription?

**Comment by elliotchance** [comment]
That does sound familiar - although it has been a while since we wrote the integration with QuickBooks so I can't confirm that. I can say that at the moment we are using sandbox companies for test - perhaps create a sandbox company and see if you can that working separately?

**Comment by natsu90** [comment]
Still same error using sandbox. Any other idea? I'm running this on localhost. I've setup `Host domain` correct, my localhost domain as `slurp.app`.

**Comment by natsu90** [comment]
I tried https://github.com/consolibyte/quickbooks-php and have no problem. And I found this blog, https://developer.intuit.com/blog/2015/02/19/oauth-for-intuit-demystified, it's using `GET` instead of `POST`. So it means this oauth service is outdated.

**Comment by elliotchance** [comment]
@natsu90 - I found the same problem today. I have put the fix into v0.8.1.

**Comment by natsu90** [comment]
@elliotchance Awesome! Thanks, it's working now.

**Pull request merged**
