### PR TITLE
Bugfix for facebook scope delimter

### PR DESCRIPTION
**Pull request by leansoft**
',’ instead of ' '

### CODE REVIEW

**Comment by elliotchance** [comment]
Can you please provide a link to the docs for this.

**Comment by leansoft** [comment]
https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow#logindialog

"scope. A comma separated list of Permissions to request from the person using your app."

**Comment by elliotchance** [comment]
Awesome, thanks for that. :+1:

**Comment by leansoft** [comment]
No problem!

**Comment by elliotchance** [comment]
https://github.com/Lusitanian/PHPoAuthLib/releases/tag/v0.5.3

**Pull request merged**
