### PR TITLE
xing responds with json encoded errors

### PR DESCRIPTION
**Pull request by hanneskaeufler**
Xing responds with json encoded errors.

https://dev.xing.com/docs/error_responses

### CODE REVIEW

**Comment by elliotchance** [comment]
Please pull in the latest `master` to get the build green so this can go in :smile:

**Comment by hanneskaeufler** [comment]
Rebased :tada:

**Comment by Lusitanian** [comment]
merged!

**Comment by elliotchance** [comment]
https://github.com/Lusitanian/PHPoAuthLib/releases/tag/v0.5.1

**Pull request merged**
