### PR TITLE
Added scopes for GMail API v1

### PR DESCRIPTION
**Pull request by pthm**

### CODE REVIEW

**Comment by elliotchance** [comment]
@pthm please pull in the latest master and clean up the code as @Lusitanian mentioned to get this merged in.

**Comment by pthm** [comment]
By the looks of things, this is already in. Just cloned master and took a look and those scopes are there.

**Comment by elliotchance** [comment]
Cool - can this be closed now?

**Comment by pthm** [comment]
Yes, apologies for not updating.

**Comment by elliotchance** [comment]
No worries, cheers for that.

**Pull request closed without merging**
