### PR TITLE
Added Eve Online OAuth2

### PR DESCRIPTION
**Pull request by Dragonrun1**
Eve Online has now made their CREST API available and uses OAuth2

### CODE REVIEW

**Comment by OrthoLoess** [comment]
Just updated the eve online module to point to the main eve server by default, as the SSO support is now fairly mainstream on EVE's end.

Are there any issues stopping this from being merged?

**Comment by Dragonrun1** [comment]
Soory I meant to change that myself before doing the pull request and forgot but as far as I know it should be all working.

**Comment by logical-and** [comment]
@Dragonrun1 Please create an example, and I will merge it in [my fork](https://github.com/logical-and/php-oauth)

**Comment by OrthoLoess** [comment]
@logical-and There is an example already, is there anything wrong with it?

**Comment by Dragonrun1** [comment]
Yeah I'm sure I include an example just like I saw from some of the others 

     On Monday, February 2, 2015 1:57 PM, OrthoLoess <notifications@github.com> wrote:
   

 @logical-and There is an example already, is there anything wrong with it?—

**Comment by OrthoLoess** [comment]
I've fixed a couple of things in this that were causing travis failure. I've also (on a separate fork) fixed the other things causing the travis failure. See PR #349 

Merge both and the project will go back to passing state.

**Comment by logical-and** [comment]
I [added](https://github.com/logical-and/php-oauth/commit/dcc141b0de3b164955bd951e31ca0978737d0e73) your service (just a bit refactored it). Will add tests soon. Can you please give me a valid credentials to application, so I will test service?

Thank you

**Comment by OrthoLoess** [comment]
To properly end-to-end test it you'd need a valid account for EVE Online. 

Was there something wrong with it that lead to the refactoring? If so, we can look at changing it on this pull request. Similarly, any reason you didn't just merge the tests in, along with everything else?

**Comment by logical-and** [comment]
@OrthoLoess No, I just updated a whole oauth library, so when I add a service - I need to remove some code from that service. :) If you can [take a look on commit](https://github.com/logical-and/php-oauth/commit/dcc141b0de3b164955bd951e31ca0978737d0e73) - you will understand what I mean. :)

**Comment by logical-and** [comment]
@OrthoLoess 
> To properly end-to-end test it you'd need a valid account for EVE Online.

Yes, I understand. I just have not valid account, so I cannot make application with valid credentials to test it. So, if you can make temporary application for me then I will be able to test EveOnline service.

Will this be difficult to do for you?

**Comment by OrthoLoess** [comment]
Sorry, I wasn't particularly clear. I could make you an app on the dev site, however doing so is against the terms of use. The bigger problem is that you still wouldn't be able to actually test it with out a valid account to log in with.

Anyone who can test it with their account, can also make an app on the dev site.

**Comment by logical-and** [comment]
OMG :). 
Well, will this not be so difficult to checkout and test the code that I merged into my repository. :) I will very appreciate it if you can.

Anyway, thank you for your commits, guys.

**Comment by OrthoLoess** [comment]
We did fairly extensive testing before committing, but I'll pull it and test again to make sure.

Happy to help where I can.

**Comment by logical-and** [comment]
Hey @OrthoLoess. I tested eve (eveonline.php), fixed something and it works like a charm now. I working now on unit testing, so will add you test soon.

Thank you for pull and credentials for Eve api. :)

**Comment by logical-and** [comment]
I added tests in update library. Thank you again. :)

**Comment by elliotchance** [comment]
@OrthoLoess this is great work - please green-ify the build before it can be merged in.

**Comment by Lusitanian** [comment]
lgtm; Travis failure was from months ago @elliotchance

**Comment by elliotchance** [comment]
@Lusitanian  #415 :smile:

**Comment by elliotchance** [comment]
https://github.com/Lusitanian/PHPoAuthLib/releases/tag/v0.4.0

**Pull request merged**
