### PR TITLE
Add instagram friend lists scope

### PR DESCRIPTION
**Pull request by sajjadrad**

### CODE REVIEW

**Comment by sajjadrad** [comment]
https://www.instagram.com/developer/authorization/

**Comment by elliotchance** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/OAuth/OAuth2/Service/Instagram.php, line 24 \[r1\]](https://reviewable.io:443/reviews/lusitanian/phpoauthlib/458#-KA7aJhhGFG5IemgMS9C:-KA7aJhhGFG5IemgMS9D:953846534) ([raw file](https://github.com/lusitanian/phpoauthlib/blob/0a9767300954c13b3594272b2dc9ed9ff01dc121/src/OAuth/OAuth2/Service/Instagram.php#L24)):*
Why did you pick `SCOPE_FRIEND_LIST` instead of `SCOPE_FOLLOWER_LIST` like the convention of the others?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/lusitanian/phpoauthlib/458)*

**Comment by sajjadrad** [comment]
@elliotchance because it's not just follower_list, it will get following lists too.

**Comment by elliotchance** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/OAuth/OAuth2/Service/Instagram.php, line 24 \[r1\]](https://reviewable.io:443/reviews/lusitanian/phpoauthlib/458#-KA7aJhhGFG5IemgMS9C:-KACtFZz_pgxhNA4kmtn:-801452802) ([raw file](https://github.com/lusitanian/phpoauthlib/blob/0a9767300954c13b3594272b2dc9ed9ff01dc121/src/OAuth/OAuth2/Service/Instagram.php#L24)):*
Please reply on the reviewable: https://reviewable.io/reviews/lusitanian/phpoauthlib/458

I'm referring to the naming convention not what the actual scope returns. The name of the constant should be indicative of the value it represents like all the other constants.

Following on from what you said it would be good to put that as a comment on the constant since that's not clear.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/lusitanian/phpoauthlib/458)*

**Comment by sajjadrad** [comment]
Const name changed.

**Comment by elliotchance** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/lusitanian/phpoauthlib/458)*

**Comment by elliotchance** [comment]
Thanks @sajjadrad! https://github.com/Lusitanian/PHPoAuthLib/releases/tag/v0.8.7

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/lusitanian/phpoauthlib/458#-:-KAHRnypZJmDUzoZIrFN:-2021630730)*

**Pull request merged**
