### PR TITLE
[RFC] Refactoring to use ivory-http-adapter

### PR DESCRIPTION
**Pull request by cmodijk**
I have started to rewrite the client interface to use egeloen/ivory-http-adapter. The reason for this is that people could pick there own client to work with this library. One other reason is that it follows the PSR-7 specs and it allows us to fix my orinonal proposal to add the Response code #144. 

All the test work as of now but I still need tot test if it really stil works with some current providers. But I would like to hear feedback.

### CODE REVIEW

**Comment by cmodijk** [comment]
Ping @Lusitanian are you still maintaining the package?

**Comment by jhuet** [comment]
Hi @cmodijk, i definitely think it's a very good idea that should be merge soon.

Do you think though that something even less coupled to ivory-http-adapter would be better ? Like only have references to the PSR-7 interfaces but not to an actual implementation of it ? We could still by default require ivory-http-adapter to make it easier to use but this would leave open to anybody to use it's own library implementing PSR-7. A bit like [Geocoder](https://github.com/geocoder-php/Geocoder#http-adapters) did ?

**Comment by cmodijk** [comment]
@jhuet You are right we should make it full PSR-7 interfaces and not implement ivory by default. I think the ivory http adapter should be a seperate package so we could require a speific version of ivory. More about this topic here http://php-and-symfony.matthiasnoback.nl/2014/04/theres-no-such-thing-as-an-optional-dependency/

But I already contacted @Lusitanian but he is currently very busy with school so I don't think it would be merged any time soon.

**Comment by logical-and** [comment]
Hey dudes. :)
Already implement the same idea at [updated library](https://github.com/logical-and/php-oauth), but with another dependency.

**Comment by jhuet** [comment]
Your library looks very promising @logical-and, i like the UserData approach you've added. To go back to the actual subject here, i think you'll also gain a lot by using a library implementing PSR-7 or by leaving the library open to the dev choosing as long as it implements PSR-7.

**Comment by logical-and** [comment]
@jhuet It's very easy to implement using different libraries now (it's just a deal with replacing Browser object). Can you make interface for PSR-7 http transporter, so I will think on how it's better to integrate with oauth library? You don't talk about simple http transporter wrapper, which only contain http object inside, right?

**Comment by cmodijk** [comment]
@logical-and I think you should use the PSR-7 interfaces in you library and remove the Buzz dependencies and if you want to provide a Buzz implementation you should create a bridge between Buzz and the PSR-7 (if buzz does not follow PSR-7) in a second library and than any library that follow's PSR-7 could be used. 
* http://php-and-symfony.matthiasnoback.nl/2014/04/theres-no-such-thing-as-an-optional-dependency/

**Comment by logical-and** [comment]
@cmodijk Actually, oauth library uses only one method - it is request() method. I don't know, does it really needed to use psr-7 compatible http transporter, if only one method used. Too much coding for such tiny result. :)

**Comment by logical-and** [comment]
@cmodijk Thanks for your links about optional deps, nice idea.

**Comment by cmodijk** [comment]
@logical-and It's al about taste of library's now when you use yours you need buzz en personaly I don't like buzz. With the PSR-7 interfaces and separating the Buzz implementation I could use ivory-http-adapter or even Guzzle. Maybe it's even a better idea to create a pull request at the buzz library so that the are implementing PSR-7 and then you can focus on the library and not on the http implementation. 

I just noticed one other major thing on you library your request method still returns a string and I want to return a Response object. Becues some API's return useful information inside the headers or even using the HTTP status codes. Thats what this pull request originally was al about.

**Comment by cmodijk** [comment]
@logical-and A amazing example of using this idea of optional deps is [SimpleBus](https://github.com/SimpleBus) from the same author as the article.

**Comment by cmodijk** [comment]
I have just migrated my repository to our company namespace https://github.com/JCID/PHPoAuthLib/tree/ivory-http-adapter

**Comment by Lusitanian** [comment]
As @logical-and noted, makes HTTP a bit too complex and adds an unnecessary dep. Optional deps would work.

**Comment by cmodijk** [comment]
I'm closing this because ivory-http-adapter is deprecared. https://github.com/php-http/httplug is Replacing i think the system needs to implement the PSR-7 specification and interfaces and not implement any clients this should be the task of an external library. We could list one in de docs to be installed but let people choose there own.

**Pull request closed without merging**
