### PR TITLE
Amazon service profile id scope.

### PR DESCRIPTION
**Pull request by mCzolko**
Just updating Amazon scopes.

### CODE REVIEW

**Comment by flavioheleno** [comment]
Would you mind referring the documentation for these scopes?

Thanks :)

**Comment by mCzolko** [comment]
I've already reffer to documentation in the code as you can see here :) https://github.com/mCzolko/PHPoAuthLib/blob/bb90d04a6df818ec553e149249f68d28a4af49f5/src/OAuth/OAuth2/Service/Amazon.php#L30

**Comment by flavioheleno** [comment]
Sorry, my bad :)

**Comment by mCzolko** [comment]
It's perfectly fine :)

**Comment by logical-and** [comment]
Just added it. Thank you guyz!

**Comment by flavioheleno** [comment]
This should be merged into the main library. @Lusitanian / @elliotchance ?

**Comment by flavioheleno** [comment]
@mCzolko hey, can you reopen the PR? I've checked the documentation and the scopes are still valid.

**Pull request closed without merging**
