### PR TITLE
Create Yahoo.php

### PR DESCRIPTION
**Pull request by geodeveloper**
Added Yahoo OAuh2 service.

### CODE REVIEW

**Comment by logical-and** [comment]
Hey. :)
Can you please open pull request at [updated library](https://github.com/logical-and/php-oauth), so I will be able to merge your changes.

**Comment by elliotchance** [comment]
Hi @geodeveloper thanks for adding this. Just a few things before this can be merged in;

1. We use 4 spaces (not tabs)
2. Each of the providers must come with unit tests.
3. The build must be green, you can see the build errors here: https://travis-ci.org/Lusitanian/PHPoAuthLib/builds/44848872

**Comment by geodeveloper** [comment]
Hi,

I've updated the file with indent 4 spaces.

**Comment by geodeveloper** [comment]
I'll add soon the unit test. ;)

**Comment by geodeveloper** [comment]
Hey @elliotchance . I've added the test too. See here: https://github.com/Lusitanian/PHPoAuthLib/pull/422

The tests are failing because it can't find the Yahoo.php file.

**Comment by geodeveloper** [comment]
I've fixed an issue, now we have all green.

**Comment by elliotchance** [comment]
Champion! :+1:

**Comment by elliotchance** [comment]
https://github.com/Lusitanian/PHPoAuthLib/releases/tag/v0.6.0

**Comment by geodeveloper** [comment]
Great :)

**Pull request merged**
